sudo: required

language: python

python:
  - "3.5"

env:
  global:
    - FLASK_CONFIG=test
    - MEMCACHED_HOST=localhost
    - MEMCACHED_PORT=11211

services:
  - docker
  - memcached

# before_install:
#   - docker build -t goosechooser/benwaonline:latest .
#   - docker run -d goosechooser/benwaonline:latest
#   - docker ps -a

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest tests

after_success:
  - docker build -t benwaonline .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag benwaonline:latest "$DOCKER_USERNAME"/benwaonline:latest;
      docker push "$DOCKER_USERNAME"/benwaonline:latest;
    else
      docker tag benwaonline:latest "$DOCKER_USERNAME"/benwaonline:dev;
      docker push "$DOCKER_USERNAME"/benwaonline:dev;
    fi