sudo: required

language: python

python:
  - "3.5"

env:
  global:
    - FLASK_CONFIG=test
    - MEMCACHED_HOST=localhost
    - MEMCACHED_PORT=11211

services:
  - docker
  - memcached

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest tests

# This would be a good spot to run tests against the docker image
after_success:
  - docker build -t benwaonline .
  # - docker run -d benwaonline:latest
  # - docker ps -a
