sudo: required

language: python

python:
  - "3.6"

env:
  global:
    - FLASK_ENV=testing
    - REDIS_HOST=localhost
    - REDIS_PORT=6379

services:
  - docker
  - redis

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - py.test --cov-config .coveragerc --cov=benwaonline --cov-report xml tests/
