sudo: required

language: python

python:
  - "3.6"

env:
  global:
    - FLASK_ENV=testing
    - REDIS_HOST=localhost
    - REDIS_PORT=6379

services:
  - docker
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - pip install .

script:
  - py.test --cov-config .coveragerc --cov=benwaonline --cov-report xml tests/
