version: '3.4'

services:
    testing:
        build:
            context: .
            target: testing
        # image: benwaonline:testing
        environment:
            - FLASK_CONFIG=test
            - API_URL=http://benwaonline-api
            - API_PORT=420
            - SECURITY_PASSWORD_SALT
            - SECRET_KEY
        command: py.test --cov-config .coveragerc --cov=benwaonline --cov-report xml tests/
        volumes:
            - ./work_dir/:/usr/src/app