"""empty message

Revision ID: ded48eab2545
Revises: 
Create Date: 2017-09-14 05:48:49.151365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded48eab2545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benwa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benwapictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('thumbnail', sa.String(length=64), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('benwa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benwa_id'], ['benwa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guestbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('benwa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benwa_id'], ['benwa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guestbook')
    op.drop_table('benwapictures')
    op.drop_table('benwa')
    op.drop_table('pool')
    # ### end Alembic commands ###
